export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const MAIN_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const BETON_ROUTE = '/beton'
export const ADMIN_PANEL_ROUTE = '/admin_panel'